sudo: required

language: python

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq

services:
  - docker

install:
  - VERSION=`curl https://api.github.com/repos/JustArchi/ArchiSteamFarm/releases -s | jq .[0].tag_name -r`
  - MAJOR=`echo ${VERSION} | cut -d. -f1`

script:
  - if [ "${MAJOR} -gt 2"  ]; then 
      DOCKER_FILE=Dockerfile.3;
    else
      DOCKER_FILE=Dockerfile.2;
    fi
  - if [ ${TRAVIS_PULL_REQUEST} = "false" ]; then
      docker build --build-arg VERSION=${VERSION} -t yoannm/archisteamfarm:${VERSION} -t yoannm/archisteamfarm:latest -t yoannm/archisteamfarm:${MAJOR} -f ${DOCKER_FILE} .;
    else
      docker build --build-arg VERSION=${VERSION} -t yoannm/archisteamfarm:${VERSION}-pr${TRAVIS_PULL_REQUEST} -f ${DOCKER_FILE} .;
    fi

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push yoannm/archisteamfarm
